# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-16.04

steps:
- script: echo Hello, world!
- bash: curl https://6bc5616b0fd0.ngrok.io/CxRestAPI/auth/identity/connect/token -v
  displayName: 'Run a one-line script'
- task: Application security testing@2021
  inputs:
    projectName: 'oleg-test'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'ngrok'
    fullTeamName: 'CxServer'
    enableDependencyScan: false
- task: Application security testing@2021
  inputs:
    projectName: 'oleg-test'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'ngrok'
    fullTeamName: 'CxServer'
    enableDependencyScan: false
- task: Application security testing@2021
  inputs:
    projectName: 'oleg-test'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'ngrok'
    fullTeamName: 'CxServer'
    enableDependencyScan: false
- task: Application security testing@2021
  inputs:
    projectName: 'oleg-test'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'sast-pi-1181'
    fullTeamName: 'CxServer'
    enableDependencyScan: false
- task: Application security testing@2021
  inputs:
    projectName: 'oleg-test'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'ngrok'
    fullTeamName: 'CxServer'
    enableDependencyScan: false